# Generated by Django 4.0.3 on 2022-04-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('ticket_price', models.FloatField(verbose_name='preço do ingresso')),
                ('start_dt', models.DateTimeField(verbose_name='início')),
                ('end_dt', models.DateTimeField(verbose_name='fim')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='organizador')),
                ('speakers', models.ManyToManyField(related_name='speaker', to=settings.AUTH_USER_MODEL, verbose_name='palestrantes')),
                ('tags', models.ManyToManyField(to='core.tag', verbose_name='tags')),
            ],
        ),
    ]
