# Generated by Django 4.0.3 on 2022-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Define se o usuário é um organizador, podem criar eventos na plataforma.', verbose_name='organizador'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_speaker',
            field=models.BooleanField(default=False, help_text='Define se o usuário é um palestrante, podem ser chamados para participar de eventos.', verbose_name='palestrante'),
        ),
    ]
